FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

ARG GA_MEASUREMENT_ID
ARG NEXT_PUBLIC_EMAILJS_SERVICEID
ARG NEXT_PUBLIC_EMAILJS_CONTACT_FORM_TEMPLATEID
ARG NEXT_PUBLIC_EMAILJS_VISIT_PORTFOLIO_TEMPLATEID
ARG NEXT_PUBLIC_EMAILJS_API_KEY
ARG NEXT_PUBLIC_VISIT_API

ENV GA_MEASUREMENT_ID=$GA_MEASUREMENT_ID
ENV NEXT_PUBLIC_EMAILJS_SERVICEID=$NEXT_PUBLIC_EMAILJS_SERVICEID
ENV NEXT_PUBLIC_EMAILJS_CONTACT_FORM_TEMPLATEID=$NEXT_PUBLIC_EMAILJS_CONTACT_FORM_TEMPLATEID
ENV NEXT_PUBLIC_EMAILJS_VISIT_PORTFOLIO_TEMPLATEID=$NEXT_PUBLIC_EMAILJS_VISIT_PORTFOLIO_TEMPLATEID
ENV NEXT_PUBLIC_EMAILJS_API_KEY=$NEXT_PUBLIC_EMAILJS_API_KEY
ENV NEXT_PUBLIC_VISIT_API=$NEXT_PUBLIC_VISIT_API

RUN npm run build

FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci --only=production && npm cache clean --force

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

EXPOSE 3000

CMD ["node", "server.js"]