export const skills = {
  frontend: [
    "React.js",
    "Next.js",
    "Capacitor.js",
    "TypeScript",
    "Redux",
    "Zustand",
    "JavaScript",
    "HTML",
    "Tailwind CSS",
    "i18next",
    "Shadcn",
    "TanStack",
    "React Router",
    "Swiper",
    "Framer Motion",
    "Material UI",
  ],
  backend: [
    "Node.js",
    "Next.js",
    "Auth.js",
    "Express.js",
    "Passport.js",
    "Zod",
    "Multer",
    "MongoDB",
    "Firestore",
    "Elasticsearch",
    "JWT",
    "Bcrypt",
    "Python",
  ],
  cloud: [
    "Git",
    "Docker",
    "GCP",
    "Cloud Run",
    "Google Buckets",
    "Artifact Registry",
    "Firebase Hosting",
    "Github Actions",
  ],
  tools: [
    "Parcel",
    "Vite",
    "NPM",
    "Vercel",
    "Jira",
    "Linear",
    "Slack",
    "Azure DevOps",
    "Postman",
    "EmailJS",
    "Sendgrid",
    "Resend",
  ],
};
