export const skills = {
  "artificial intelligence": [
    "Agents",
    "Google ADK",
    "Multi-Agents",
    "LLMs",
    "MCP",
    "OpenAI API",
  ],
  database: [
    "MongoDB",
    "Firestore",
    "BigQuery",
    "SQL",
    "DynamoDB",
    "Elasticsearch",
  ],
  cloud: [
    "Git",
    "Docker",
    "GCP",
    "AWS",
    "Firebase Hosting",
    "Cloud Run",
    "Agent Engine",
    "Cloud Tasks",
    "Cloud Triggers",
    "S3 Buckets",
    "Github Actions",
    "Cloudfare",
  ],
  backend: [
    "Node.js",
    "Next.js",
    "Python",
    "Express.js",
    "Auth.js",
    "Passport.js",
    "Zod",
    "CORS",
    "JWT",
    "Bcrypt",
  ],
  frontend: [
    "React.js",
    "Next.js",
    "Capacitor.js",
    "TypeScript",
    "Redux",
    "Zustand",
    "JavaScript",
    "HTML",
    "Tailwind CSS",
    "i18next",
    "Shadcn",
    "TanStack",
    "React Router",
    "Swiper",
    "Framer Motion",
    "Material UI",
  ],
  tools: [
    "Parcel",
    "Vite",
    "NPM",
    "Vercel",
    "Github",
    "Jira",
    "Linear",
    "Slack",
    "Azure DevOps",
    "Postman",
    "EmailJS",
    "Sendgrid",
    "Resend",
  ],
};
