export const techStack = {
  frontend: [
    "React.js",
    "Next.js",
    "TypeScript",
    "Redux",
    "JavaScript",
    "HTML",
    "Tailwind CSS",
    "i18next",
    "React Router",
    "GraphQL",
    "Material UI",
  ],
  backend: ["Node.js", "Next.js", "Auth.js", "Express.js", "MongoDB", "JWT"],
  tools: [
    "Parcel",
    "Vite",
    "NPM",
    "Vercel",
    "Git",
    "Jira",
    "Azure DevOps",
    "Postman",
    "EmailJS",
  ],
};
